[package]
name = "edhoc-crypto-psa"
version = "0.1.0"
edition = "2021"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license = "BSD"
description = "EDHOC crypto library PSA backend"

[dependencies]
edhoc-consts = { path = "../../consts" }
hacspec-lib = { version = "0.1.0-beta.1", default-features = false, features = [ "alloc" ] }
psa-crypto = { version = "0.9.2" }

[features]
baremetal = [ "psa-crypto/baremetal" ]
hacspec = [ ]
rust = [ ]
