[package]
name = "edhoc-ead-zeroconf"
version = "0.1.0"
edition = "2021"
authors = ["Geovane Fedrecheski <geonnave@gmail.com>"]
license = "BSD"
description = "EDHOC EAD zeroconf (draf-lake-authz)"

[dependencies]
edhoc-consts = { path = "../../consts" }
hexlit = "0.5.3"
